[versions]
agp = "8.2.0"
kotlin = "1.9.21"
lyricGetterApi = "6.0.0"
smartspacer = "1.0.3"

[libraries]
lyricGetterApi = { module = "com.github.xiaowine:Lyric-Getter-Api", version.ref = "lyricGetterApi" }
smartspacer-sdkplugin = { module = "com.kieronquinn.smartspacer:sdk-plugin", version.ref = "smartspacer" }
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

